language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"

jdk:
  - openjdk10

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Download SDK
  - yes | sdkmanager "tools"
  - yes | sdkmanager "platform-tools" &>/dev/null
  # Download emulator
  - yes | sdkmanager "platforms;android-21" &>/dev/null
  - yes | sdkmanager "system-images;android-21;default;x86_64" &>/dev/null
  # Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null
  # Setup emulator
  - echo "no" | avdmanager create avd -n test -k "system-images;android-21;default;x86_64" -c 200M -f &>/dev/null
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-accel -no-snapshot -no-window -camera-back none -camera-front none & &>/dev/null

install:
  # Build debug and release(run proguard)
  - ./gradlew clean ktlintCheck assemble lintDebug assembleDebugAndroidTest -Pci -s --scan

before_script:
  # Make sure the emulator is available
  - android-wait-for-emulator

script:
  - ./gradlew testDebug connectedDebugAndroidTest -Pci -s --scan

branches:
  except:
    - gh-pages

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

