language: android

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=8

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      env: ANDROID_HOME=/usr/local/opt/android-sdk
      osx_image: xcode8

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install android-sdk; fi

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

before_script:
  # Setup emulator
  - if [ "$TRAVIS_OS_NAME" = linux ]; then .buildscript/setup-emulator.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./gradlew clean testDebug assembleDebugAndroidTest jacocoDebugReport -Pci --scan --stacktrace --parallel; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then ./gradlew clean testDebug connectedDebugAndroidTest createDebugCoverageReport jacocoDebugReport coveralls -Pci --scan --stacktrace --parallel; fi

sudo: required

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
