language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

jdk:
  - oraclejdk8

before_install:
  # Download SDK
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platform-tools"
  - echo yes | sdkmanager "build-tools;26.0.1"
  - echo yes | sdkmanager "platforms;android-26"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;android;m2repository"
  # Download emulator
  - echo yes | sdkmanager "platforms;android-19"
  - echo yes | sdkmanager "system-images;android-19;default;armeabi-v7a"
  - echo yes | sdkmanager --licenses
  # Setup emulator
  - echo no | avdmanager create avd --force -n test -k "system-images;android-19;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install:
  # Build debug and release(run proguard)
  - ./gradlew clean assemble assembleAndroidTest -Pci --stacktrace --scan

before_script:
  # Make sure the emulator is available
  - android-wait-for-emulator

  # Turn off animations
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &

  # For Multidex issue for devices API < 19
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell stop installd
  - adb shell start installd

  # Wake up
  - adb shell input keyevent 82 &

script:
  # Run all checks
  - ./gradlew check connectedCheck createDebugCoverageReport jacocoDebugReport coveralls -Pci --stacktrace --scan

branches:
  except:
    - gh-pages

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
